// <auto-generated />
namespace InventoryServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRemarkstoSalesInvoiceandPurchaseOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRemarkstoSalesInvoiceandPurchaseOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201812190315173_Add-Remarks-to-SalesInvoice-and-PurchaseOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
